### ISSUE TITLE
request option to be able to select text to copy in a text editor

### ISSUE THREAD

**Issue by Jonathan003** [sgriffin53/ravenopeningsexplorer#6]
For some reason it is not possible to select the text with annotations in raven opening explorer. I would like to request that so I can copy some annotations to past them as annotations in a pgn file for example.

**Comment by sgriffin53** [comment]
Thanks for the suggestion, I'll consider it for the next version. It might not be possible due to the way the tkhtmlview widget works, but I'll see if I can make a workaround.
